### GET ALL Products
GET http://localhost:3000/api/products


### GET Single Products
GET http://localhost:3000/api/products/1

### DELETE Single Products
DELETE http://localhost:3000/api/products/2

### GET ALL Products
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name":"Iphone 5",
    "price":45646,
    "categoryID": 1
}


